name: Deploy Static Site to Pages

on:
  push:
    branches: ["main"]
  # Permite rodar o workflow manualmente na aba Actions
  workflow_dispatch:

# Permissões exatas necessárias para o GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Evita que múltiplos deploys rodem ao mesmo tempo e quebrem o processo
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        
      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v5
        
      - name: Fazer upload dos arquivos (Artefato)
        uses: actions/upload-pages-artifact@v3
        with:
          # Faz o upload da pasta raiz do seu repositório
          path: '.'
          
      - name: Fazer o Deploy para o GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
